//! Shared license verification for Modem Cat.
//!
//! Provides Ed25519 (via `ring`) signature verification and license types used
//! by both the main Modem Cat application (`src-tauri`) and the license
//! generator tool (`tools/license-gen/`).

use ring::signature::{self, KeyPair, UnparsedPublicKey};
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Generated by the license-gen tool. Replace before release.
/// ⚠ Current value is a placeholder (all zeros).
pub const PUBLIC_KEY_BYTES: [u8; 32] = [
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
];

/// Complete license file as stored on disk (JSON).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct License {
    pub version: u32,
    /// Base64-encoded JSON payload.
    pub payload: String,
    /// Base64-encoded 64-byte Ed25519 signature.
    pub signature: String,
}

/// Decoded license payload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LicensePayload {
    /// Target machine MAC address (uppercase hex, no separators).
    pub mac: String,
    /// Unix timestamp when the license was issued.
    pub issued_at: i64,
    /// Unix timestamp when the license expires.  `0` = never.
    pub expires_at: i64,
    /// Feature flags.
    pub features: LicenseFeatures,
    /// Licensee name (display only).
    #[serde(default)]
    pub licensee: String,
    /// Free-form note.
    #[serde(default)]
    pub note: String,
}

/// Feature flags controlling which functionality is unlocked.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LicenseFeatures {
    #[serde(default)]
    pub factory_mode: bool,
    #[serde(default)]
    pub firmware_download: bool,
}

/// Status returned to the frontend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LicenseStatus {
    pub valid: bool,
    pub factory_mode: bool,
    pub firmware_download: bool,
    pub licensee: String,
    pub expires_at: i64,
    pub mac: String,
    pub error: String,
}

#[derive(Debug, Clone)]
pub enum LicenseError {
    Io(String),
    Parse(String),
    InvalidSignature,
    Expired,
    MacMismatch { expected: String, got: String },
    UnsupportedVersion(u32),
    Base64(String),
}

impl std::fmt::Display for LicenseError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io(e) => write!(f, "读取 License 文件失败: {e}"),
            Self::Parse(e) => write!(f, "License 格式错误: {e}"),
            Self::InvalidSignature => write!(f, "License 签名无效（文件可能被篡改）"),
            Self::Expired => write!(f, "License 已过期"),
            Self::MacMismatch { expected, got } => {
                write!(f, "MAC 地址不匹配: 期望 {expected}, 实际 {got}")
            }
            Self::UnsupportedVersion(v) => write!(f, "不支持的 License 版本: {v}"),
            Self::Base64(e) => write!(f, "Base64 解码失败: {e}"),
        }
    }
}

/// One-stop load + verify signature + check expiry + check MAC.
pub fn load_and_verify<P: AsRef<Path>>(path: P) -> Result<LicensePayload, LicenseError> {
    let raw = std::fs::read_to_string(path.as_ref())
        .map_err(|e| LicenseError::Io(e.to_string()))?;
    let license: License =
        serde_json::from_str(&raw).map_err(|e| LicenseError::Parse(e.to_string()))?;
    verify_license(&license)?;
    let payload = license.payload()?;
    payload.check_expiry()?;
    payload.check_mac()?;
    Ok(payload)
}

/// Verify the Ed25519 signature. Does NOT check expiry or MAC.
pub fn verify_license(license: &License) -> Result<(), LicenseError> {
    if license.version != 1 {
        return Err(LicenseError::UnsupportedVersion(license.version));
    }
    let sig_bytes = base64_decode(&license.signature)?;
    let payload_bytes = base64_decode(&license.payload)?;
    let public_key = UnparsedPublicKey::new(&signature::ED25519, &PUBLIC_KEY_BYTES);
    public_key
        .verify(&payload_bytes, &sig_bytes)
        .map_err(|_| LicenseError::InvalidSignature)?;
    Ok(())
}

impl License {
    pub fn payload(&self) -> Result<LicensePayload, LicenseError> {
        let json_bytes = base64_decode(&self.payload)?;
        serde_json::from_slice(&json_bytes).map_err(|e| LicenseError::Parse(e.to_string()))
    }
}

impl LicensePayload {
    pub fn check_expiry(&self) -> Result<(), LicenseError> {
        if self.expires_at == 0 {
            return Ok(());
        }
        let now = chrono::Utc::now().timestamp();
        if now > self.expires_at {
            return Err(LicenseError::Expired);
        }
        Ok(())
    }

    pub fn check_mac(&self) -> Result<(), LicenseError> {
        if self.mac.is_empty() {
            return Ok(());
        }
        let expected = self.mac.to_uppercase();
        let current = get_current_mac()?;
        if expected != current {
            return Err(LicenseError::MacMismatch {
                expected,
                got: current,
            });
        }
        Ok(())
    }
}

fn get_current_mac() -> Result<String, LicenseError> {
    match mac_address::get_mac_address() {
        Ok(Some(mac)) => {
            let bytes = mac.bytes();
            Ok(bytes
                .iter()
                .map(|b| format!("{:02X}", b))
                .collect::<String>())
        }
        Ok(None) => Err(LicenseError::Io("未检测到网卡 MAC 地址".into())),
        Err(e) => Err(LicenseError::Io(format!("获取 MAC 地址失败: {e}"))),
    }
}

/// Serialize to deterministic compact JSON (sorted keys, no whitespace).
pub fn canonical_json<T: Serialize>(value: &T) -> Result<Vec<u8>, LicenseError> {
    let mut v = serde_json::to_value(value).map_err(|e| LicenseError::Parse(e.to_string()))?;
    sort_json_keys(&mut v);
    serde_json::to_vec(&v).map_err(|e| LicenseError::Parse(e.to_string()))
}

fn sort_json_keys(v: &mut serde_json::Value) {
    if let serde_json::Value::Object(map) = v {
        let old = std::mem::take(map);
        let mut entries: Vec<_> = old.into_iter().collect();
        entries.sort_by(|a, b| a.0.cmp(&b.0));
        for (k, mut val) in entries {
            sort_json_keys(&mut val);
            map.insert(k, val);
        }
    }
}

fn base64_decode(input: &str) -> Result<Vec<u8>, LicenseError> {
    use base64::Engine;
    base64::engine::general_purpose::STANDARD
        .decode(input)
        .map_err(|e| LicenseError::Base64(e.to_string()))
}

pub fn base64_encode(data: &[u8]) -> String {
    use base64::Engine;
    base64::engine::general_purpose::STANDARD.encode(data)
}

/// Generate a fresh Ed25519 key pair. Returns (pkcs8_der, public_key_32_bytes).
/// Only used by license-gen during initial setup.
pub fn generate_key_pair() -> Result<(Vec<u8>, [u8; 32]), String> {
    let rng = ring::rand::SystemRandom::new();
    let pkcs8 = ring::signature::Ed25519KeyPair::generate_pkcs8(&rng)
        .map_err(|e| format!("密钥生成失败: {e}"))?;
    let key_pair = ring::signature::Ed25519KeyPair::from_pkcs8(pkcs8.as_ref())
        .map_err(|e| format!("密钥解析失败: {e}"))?;
    let pub_key_bytes: [u8; 32] = key_pair
        .public_key()
        .as_ref()
        .try_into()
        .map_err(|_| "公钥长度错误".to_string())?;
    Ok((pkcs8.as_ref().to_vec(), pub_key_bytes))
}

/// Sign a message with a PKCS#8 Ed25519 private key.
/// Only used by license-gen.
pub fn sign_message(pkcs8_der: &[u8], message: &[u8]) -> Result<Vec<u8>, String> {
    let key_pair = ring::signature::Ed25519KeyPair::from_pkcs8(pkcs8_der)
        .map_err(|e| format!("私钥加载失败: {e}"))?;
    Ok(key_pair.sign(message).as_ref().to_vec())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test_license(
        factory: bool,
        firmware: bool,
        expires_at: i64,
        mac: &str,
    ) -> (License, [u8; 32]) {
        let (pkcs8, pub_key) = generate_key_pair().unwrap();
        let payload = LicensePayload {
            mac: mac.into(),
            issued_at: 1718496000,
            expires_at,
            features: LicenseFeatures {
                factory_mode: factory,
                firmware_download: firmware,
            },
            licensee: "Test".into(),
            note: "".into(),
        };
        let payload_bytes = canonical_json(&payload).unwrap();
        let signature = sign_message(&pkcs8, &payload_bytes).unwrap();
        let license = License {
            version: 1,
            payload: base64_encode(&payload_bytes),
            signature: base64_encode(&signature),
        };
        (license, pub_key)
    }

    #[test]
    fn test_verify_valid_license() {
        let (license, pub_key) = make_test_license(true, true, 0, "");
        let sig_bytes = base64_decode(&license.signature).unwrap();
        let payload_bytes = base64_decode(&license.payload).unwrap();
        let public_key = UnparsedPublicKey::new(&signature::ED25519, &pub_key);
        public_key.verify(&payload_bytes, &sig_bytes).unwrap();

        let decoded = license.payload().unwrap();
        assert_eq!(decoded.features.factory_mode, true);
    }

    #[test]
    fn test_tampered_sig_rejected() {
        let (license, pub_key) = make_test_license(true, false, 0, "");
        let mut sig_bytes = base64_decode(&license.signature).unwrap();
        sig_bytes[0] ^= 0xFF;
        let payload_bytes = base64_decode(&license.payload).unwrap();
        let public_key = UnparsedPublicKey::new(&signature::ED25519, &pub_key);
        assert!(public_key.verify(&payload_bytes, &sig_bytes).is_err());
    }

    #[test]
    fn test_tampered_payload_rejected() {
        let (mut license, pub_key) = make_test_license(true, false, 0, "");
        let mut payload_bytes = base64_decode(&license.payload).unwrap();
        payload_bytes[10] ^= 0x01;
        license.payload = base64_encode(&payload_bytes);
        let sig_bytes = base64_decode(&license.signature).unwrap();
        let public_key = UnparsedPublicKey::new(&signature::ED25519, &pub_key);
        assert!(public_key.verify(&payload_bytes, &sig_bytes).is_err());
    }

    #[test]
    fn test_expired() {
        let past = chrono::Utc::now().timestamp() - 3600;
        let payload = LicensePayload {
            mac: "".into(),
            issued_at: past - 86400,
            expires_at: past,
            features: LicenseFeatures {
                factory_mode: false,
                firmware_download: false,
            },
            licensee: "".into(),
            note: "".into(),
        };
        assert!(matches!(payload.check_expiry(), Err(LicenseError::Expired)));
    }

    #[test]
    fn test_never_expires() {
        let payload = LicensePayload {
            mac: "".into(),
            issued_at: 0,
            expires_at: 0,
            features: LicenseFeatures {
                factory_mode: false,
                firmware_download: false,
            },
            licensee: "".into(),
            note: "".into(),
        };
        assert!(payload.check_expiry().is_ok());
    }

    #[test]
    fn test_canonical_json() {
        let feat = LicenseFeatures {
            factory_mode: true,
            firmware_download: false,
        };
        let a = canonical_json(&feat).unwrap();
        let b = canonical_json(&feat).unwrap();
        assert_eq!(a, b);
        let expected = br#"{"factory_mode":true,"firmware_download":false}"#;
        assert_eq!(a, expected);
    }

    #[test]
    fn test_unsupported_version() {
        let license = License {
            version: 99,
            payload: "".into(),
            signature: "".into(),
        };
        assert!(matches!(
            verify_license(&license),
            Err(LicenseError::UnsupportedVersion(99))
        ));
    }

    #[test]
    fn test_base64_roundtrip() {
        let data = b"hello world";
        let encoded = base64_encode(data);
        let decoded = base64_decode(&encoded).unwrap();
        assert_eq!(decoded, data);
    }
}
